#!/usr/bin/env bash

installdeps () {
  local deps=$@
  local extra
  local manager="npm"
  if [ -f yarn.lock ] ; then
    manager='yarn'
  fi

  if [[ -n "${deps[*]}" ]] ; then
    echo '';
    echo '-----> Installing global dependencies';
    echo '';
    echo "       $deps"
    echo '';

    if [[ "$manager" -eq "yarn" ]]; then
      yarn global add $deps
    else
      npm install -g $deps
    fi
  fi
}

installdeps $@;
