#!/usr/bin/env bash

get_script_dir () {
  SOURCE="${BASH_SOURCE[0]}"
  # While $SOURCE is a symlink, resolve it
  while [ -h "$SOURCE" ]; do
      DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
      SOURCE="$( readlink "$SOURCE" )"
      # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
      [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo "$DIR"
}

nodejs_build_script () {
echo "NPM_CONFIG_PRODUCTION=false NODE_ENV=development /fjord/builds/nodejs/compile;
echo \"NPM_CONFIG_PRODUCTION=false;NODE_ENV=development\" >> /root/.profile.d/nodejs.sh;
source /root/.profile.d/nodejs.sh;
"
}

python_build_script () {
echo "/fjord/builds/python/compile;
echo \"export PATH=/app/.heroku/python/bin:\$PATH\" >> /app/.profile.d/python.sh;
source /app/.profile.d/python.sh;
source /app/.profile.d/python.gunicorn.sh;
"
}

determine_languages () {
  if [ -f "./Gemfile" ]; then
    echo 'ruby coming soon!'
    exit 0
  fi
  if [ -f "./requirements.txt" ]; then
    languages="$languages python"
  fi
  if [ -f "package.json" ]; then
    languages="$languages nodejs"
  fi
}

# $language_build_script
# /fjord/builds/$language/deps $deps;
# echo \"\n-----> Exporting $language env vars to bash\";
# bash;

start_runner () {
  local cmd=$1
  local port
  local deps="${@:2}"
  local app_dir=`pwd`
  local languages=""

  determine_languages;

  if [[ ! -z $languages ]]; then
    combined_language_script=""

    for language in $languages; do
      echo "build: $language app"
      combined_language_script="$combined_language_script $("$language"_build_script)"
    done

    if [[ ! -z $deps ]]; then
      for depmang in $deps; do
        # echo $depmang
        if [[ $depmang =~ ^--port= ]]; then
          port="${depmang/--port=/}"
          echo "expose: port $port"
        elif [[ $depmang =~ ^--npm= ]]; then
          echo "install: npm global dependencies"
          lang_deps="${depmang/--npm=/}"
          lang_deps="${lang_deps/,/ }"
          lang_dep_script="npm install -g $lang_deps;"
          combined_language_script="$combined_language_script $lang_dep_script"
        elif [[ $depmang =~ ^--pip= ]]; then
          echo "install: pip user dependencies"
          lang_deps="${depmang/--pip=/}"
          lang_deps="${lang_deps/,/ }"
          lang_dep_script="pip install -u $lang_deps;"
          combined_language_script="$combined_language_script $lang_dep_script"
        fi
      done
    fi

    build_script="$combined_language_script
      echo '-----> Change directory to app source';
      echo '';
      cd /src;
      bash;"

    # echo $combined_build_script;
    # echo $build_script

    docker run -p 127.0.0.1:$port:$port \
                -v "$(get_script_dir)/buildpacks":/buildpacks:ro \
                -v $(get_script_dir):/fjord:ro \
                -v ${app_dir}:/src:rw \
                --rm \
                -it \
                -e "STACK=heroku-16" \
                heroku/heroku:16 \
                bash -c "$build_script"
  fi
  exit 1
}

sync_buildpacks () {
  mkdir -p "$(get_script_dir)/buildpacks"

  languages="nodejs python ruby"

  for language in $languages; do
    echo "syncing $language buildpack"
    lang_buildpack_dir="$(get_script_dir)/buildpacks/heroku-buildpack-$language"
    if [ -d "$lang_buildpack_dir" ]; then
      git --work-tree=$lang_buildpack_dir --git-dir=$lang_buildpack_dir/.git pull origin master
    else
      mkdir -p $lang_buildpack_dir
      git clone "https://github.com/heroku/heroku-buildpack-$language" $lang_buildpack_dir
    fi
    echo ''
  done
}

router () {
  if [[ $1 = "sync" ]]; then
    sync_buildpacks
  elif [[ $1 = "build"  ]]; then
    start_runner $@
  else
    # echo "Run fj help for usage"
    echo "Command $1 not known"
  fi
}

router $@;
