#!/usr/bin/env bash

installdeps () {
  local deps=$@

  if [[ -n "${deps[*]}" ]] ; then
    echo '';
    echo '-----> Installing global dependencies';
    echo '';
    echo "       $deps"
    echo '';

    pip install $deps
  fi
}

installdeps $@;
