#!/usr/bin/env bash

mktmpdir() {
  local dir=$(mktemp -t $1XXXXX)
  rm -rf $dir
  mkdir $dir
  echo $dir
}

compile() {
  language=$1
  local bp_dir=$(mktmpdir "buildpack")
  local build_dir=$(mktmpdir "build")
  local cache_dir=$(mktmpdir "cache")
  echo ""
  echo "Compiling $language app in $build_dir"
  echo "(caching in $cache_dir)"
  cp -a /fjord/buildpacks/heroku-buildpack-$language/* ${bp_dir}
  cp -a /src/. ${build_dir}

  if [[ $language = "ruby" ]]; then
    export CURL_TIMEOUT=120
    export CURL_CONNECT_TIMEOUT=15
  fi

  if [[ $language = "python" ]]; then
    echo "cats" >> "$build_dir/requirements.txt"
  fi

  "$bp_dir/bin/compile" "$build_dir" "$cache_dir"

  mkdir -p /root/.profile.d
  cp ${build_dir}/.profile.d/* /root/.profile.d

  if [[ $language = "ruby" ]]; then
    mkdir -p /root/bin
    cp -r ${build_dir}/bin/* /root/bin
    mkdir -p /root/vendor
    cp -r ${build_dir}/vendor/* /root/vendor
  else
    mkdir -p /root/.heroku
    cp -r ${build_dir}/.heroku/* /root/.heroku
  fi

  if [[ $language = "nodejs" ]]; then
    rm -fr /src/node_modules
    mv ${build_dir}/node_modules /src
  fi
}

compile $@
